// généré automatiquement par build_temples.js
const staticTemples = [
  {
    id: 1,
    x: 487,
    y: 507,
    name: 'Lissus',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 2,
    x: 534,
    y: 487,
    name: 'Gangra',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 3,
    x: 475,
    y: 532,
    name: 'Percote',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 4,
    x: 486,
    y: 479,
    name: 'Thronium',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Combattants a l\'epee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 5,
    x: 528,
    y: 454,
    name: 'Thèbes',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 6,
    x: 487,
    y: 560,
    name: 'Dimale',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 7,
    x: 511,
    y: 559,
    name: 'Myre',
    type: 'NAZE',
    bonus: 'Retour des Enfers rend 15% d\'unites en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 8,
    x: 502,
    y: 455,
    name: 'Parthenopolis',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: true
  },
  {
    id: 9,
    x: 554,
    y: 504,
    name: 'Tomis',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 10,
    x: 455,
    y: 432,
    name: 'Dascylion',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 11,
    x: 456,
    y: 571,
    name: 'Selinus',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 12,
    x: 432,
    y: 490,
    name: 'Assus',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 13,
    x: 583,
    y: 529,
    name: 'Hermione',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 14,
    x: 581,
    y: 485,
    name: 'Amphicaea',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 15,
    x: 551,
    y: 436,
    name: 'Histria',
    type: 'OFF T',
    bonus: 'Augmente la valeur offensive de toutes les unites terrestres non mythiques de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 16,
    x: 430,
    y: 513,
    name: 'Lapithos',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 17,
    x: 404,
    y: 530,
    name: 'Ithaque',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 18,
    x: 546,
    y: 597,
    name: 'Amphigeneia',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 19,
    x: 468,
    y: 589,
    name: 'Oenoe',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Meduses de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 20,
    x: 400,
    y: 501,
    name: 'Anthedon',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Sirenes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 21,
    x: 417,
    y: 461,
    name: 'Dodone',
    type: 'NAZE',
    bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 22,
    x: 603,
    y: 494,
    name: 'Kelenderis',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 23,
    x: 569,
    y: 580,
    name: 'Haliarte',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 24,
    x: 489,
    y: 597,
    name: 'Tenedos',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 25,
    x: 402,
    y: 476,
    name: 'Sozopolis',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 26,
    x: 517,
    y: 374,
    name: 'Priene',
    type: 'PROD NAV',
    bonus: 'Augmente l\'effet de l\'appel de la mer de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 27,
    x: 399,
    y: 575,
    name: 'Eubea',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Spartes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 28,
    x: 611,
    y: 574,
    name: 'Rhêgion',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 29,
    x: 605,
    y: 433,
    name: 'Laodicea',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 30,
    x: 512,
    y: 629,
    name: 'Koukounaries',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 31,
    x: 372,
    y: 503,
    name: 'Panticapaeum',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 32,
    x: 601,
    y: 412,
    name: 'Orchomene',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 33,
    x: 490,
    y: 369,
    name: 'Cynossema',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 34,
    x: 380,
    y: 460,
    name: 'Scione',
    type: 'OFF NAV',
    bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 35,
    x: 469,
    y: 389,
    name: 'Borysthenes',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 36,
    x: 409,
    y: 423,
    name: 'Samos',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 37,
    x: 375,
    y: 419,
    name: 'Ambracie',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Spartes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 38,
    x: 502,
    y: 652,
    name: 'Amphissa',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 39,
    x: 360,
    y: 484,
    name: 'Mulai',
    type: 'OFF NAV',
    bonus: 'Ameliore la force de vent favorable de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 40,
    x: 433,
    y: 627,
    name: 'Naupactus',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 41,
    x: 550,
    y: 632,
    name: 'Palaikastro',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 42,
    x: 646,
    y: 472,
    name: 'Masis',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 43,
    x: 367,
    y: 551,
    name: 'Maroneia',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 44,
    x: 400,
    y: 404,
    name: 'Vathypetros',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 45,
    x: 526,
    y: 346,
    name: 'Kourion',
    type: 'NAZE',
    bonus: 'Mariage donne 120 ressources en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 46,
    x: 470,
    y: 362,
    name: 'Kallatis',
    type: 'OFF NAV',
    bonus: 'Augmente la valeur offensive de toutes les unites navales de 5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 47,
    x: 578,
    y: 369,
    name: 'Akragas',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 48,
    x: 438,
    y: 371,
    name: 'Mylasa',
    type: 'OFF T',
    bonus: 'Force heroique augmente l\'attaque de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 49,
    x: 626,
    y: 440,
    name: 'Thurii',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 50,
    x: 640,
    y: 501,
    name: 'Tenea',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 51,
    x: 667,
    y: 512,
    name: 'Odessos',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 52,
    x: 335,
    y: 497,
    name: 'Gortyn',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 53,
    x: 338,
    y: 457,
    name: 'Rhodes',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 54,
    x: 661,
    y: 457,
    name: 'Mutilene',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Erinyes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 55,
    x: 396,
    y: 381,
    name: 'Doriskos',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 56,
    x: 387,
    y: 628,
    name: 'Phaselis',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 57,
    x: 351,
    y: 591,
    name: 'Lefkandi',
    type: 'PROD NAV',
    bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 58,
    x: 613,
    y: 377,
    name: 'Argyroupoli',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 59,
    x: 579,
    y: 638,
    name: 'Pixous',
    type: 'PROD T',
    bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 60,
    x: 642,
    y: 579,
    name: 'Tanagra',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 20%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 61,
    x: 549,
    y: 350,
    name: 'Lekhaion',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 62,
    x: 350,
    y: 569,
    name: 'Orestias',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement bireme de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 63,
    x: 567,
    y: 340,
    name: 'Pitane',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 64,
    x: 669,
    y: 485,
    name: 'Bhrytos',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 65,
    x: 648,
    y: 409,
    name: 'Olynthus',
    type: 'PROD NAV',
    bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 66,
    x: 433,
    y: 341,
    name: 'Messene',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 67,
    x: 504,
    y: 303,
    name: 'Zakynthos',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 68,
    x: 687,
    y: 564,
    name: 'Heraclea',
    type: 'OFF T',
    bonus: 'Augmente la valeur offensive de toutes les unites terrestres non mythiques de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 69,
    x: 321,
    y: 438,
    name: 'Élis',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 70,
    x: 643,
    y: 360,
    name: 'Smyrna',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Cavaliers de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 71,
    x: 308,
    y: 466,
    name: 'Chalcis',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 72,
    x: 363,
    y: 639,
    name: 'Cnide',
    type: 'OFF NAV',
    bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 73,
    x: 331,
    y: 609,
    name: 'Argos',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 74,
    x: 648,
    y: 623,
    name: 'Kalamata',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 75,
    x: 451,
    y: 674,
    name: 'Malacca',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 76,
    x: 353,
    y: 369,
    name: 'Agde',
    type: 'NAZE',
    bonus: 'Augmente les valeurs offensive et defensive de Satyres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 77,
    x: 476,
    y: 688,
    name: 'Pharos',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 78,
    x: 533,
    y: 315,
    name: 'Tylissos',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 79,
    x: 507,
    y: 694,
    name: 'Amaseia',
    type: 'NAZE',
    bonus: 'Retour des Enfers rend 15% d\'unites en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 80,
    x: 674,
    y: 430,
    name: 'Myos',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 81,
    x: 582,
    y: 661,
    name: 'Pyrgos',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 82,
    x: 346,
    y: 628,
    name: 'Stymphalos',
    type: 'OFF T',
    bonus: 'Augmente le bonus de concentration de la chasseresse de 10% supplementaires',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 83,
    x: 670,
    y: 597,
    name: 'Thoricus',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 84,
    x: 656,
    y: 380,
    name: 'Athmonia',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 85,
    x: 701,
    y: 591,
    name: 'Kasmenai',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 86,
    x: 289,
    y: 564,
    name: 'Kimmerikon',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 87,
    x: 524,
    y: 719,
    name: 'Bassae',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 88,
    x: 584,
    y: 313,
    name: 'Samothrace',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 89,
    x: 358,
    y: 668,
    name: 'Alalcomenae',
    type: 'PROD T',
    bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 90,
    x: 369,
    y: 333,
    name: 'Halieis',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Frondeurs de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 91,
    x: 332,
    y: 354,
    name: 'Monastiraki',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 92,
    x: 518,
    y: 284,
    name: 'Hyele',
    type: 'OFF NAV',
    bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 93,
    x: 612,
    y: 686,
    name: 'Agrinion',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 94,
    x: 696,
    y: 446,
    name: 'Troie',
    type: 'NAZE',
    bonus: 'Augmente les valeurs offensive et defensive de Hydres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 95,
    x: 655,
    y: 647,
    name: 'Rizinia',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de toutes les unites Mythique de 5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 96,
    x: 282,
    y: 459,
    name: 'Edessa',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Combattants a l\'epee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 97,
    x: 553,
    y: 304,
    name: 'Cythera',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Cavaliers de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 98,
    x: 719,
    y: 467,
    name: 'Akroinon',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 99,
    x: 320,
    y: 627,
    name: 'Sparte',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 100,
    x: 590,
    y: 705,
    name: 'Kilkís',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Hoplites de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 101,
    x: 302,
    y: 398,
    name: 'Taras',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 102,
    x: 722,
    y: 518,
    name: 'Akrai',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 103,
    x: 297,
    y: 584,
    name: 'Heliopolis',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 104,
    x: 296,
    y: 493,
    name: 'Mallia',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 105,
    x: 374,
    y: 307,
    name: 'Itanos',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 106,
    x: 641,
    y: 682,
    name: 'Mesembria',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 107,
    x: 349,
    y: 329,
    name: 'Methana',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 108,
    x: 402,
    y: 275,
    name: 'Gournia',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 109,
    x: 699,
    y: 361,
    name: 'Nymphaion',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 110,
    x: 258,
    y: 536,
    name: 'Pandosia',
    type: 'PROD T',
    bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 111,
    x: 568,
    y: 264,
    name: 'Dyme',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 112,
    x: 721,
    y: 436,
    name: 'Pactye',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 113,
    x: 303,
    y: 370,
    name: 'Gonnos',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 114,
    x: 746,
    y: 519,
    name: 'Naucratis',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 115,
    x: 665,
    y: 334,
    name: 'Platees',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 116,
    x: 740,
    y: 485,
    name: 'Antipatrea',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 117,
    x: 263,
    y: 434,
    name: 'Metapontum',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 118,
    x: 500,
    y: 726,
    name: 'Kepoi',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 119,
    x: 432,
    y: 277,
    name: 'Pseira',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 120,
    x: 724,
    y: 590,
    name: 'Magnesia',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 121,
    x: 286,
    y: 602,
    name: 'Ephyra',
    type: 'NAZE',
    bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 122,
    x: 735,
    y: 553,
    name: 'Bouthroton',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Meduses de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 123,
    x: 428,
    y: 716,
    name: 'Methumna',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 124,
    x: 579,
    y: 287,
    name: 'Sicyon',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 125,
    x: 282,
    y: 413,
    name: 'Patras',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 126,
    x: 713,
    y: 400,
    name: 'Ankon',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 127,
    x: 648,
    y: 282,
    name: 'Megare',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 128,
    x: 678,
    y: 312,
    name: 'Leibethra',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 129,
    x: 278,
    y: 364,
    name: 'Hyettos',
    type: 'NAZE',
    bonus: 'Augmente les valeurs offensive et defensive de Centaures de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 130,
    x: 449,
    y: 242,
    name: 'Morgantina',
    type: 'OFF NAV',
    bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 131,
    x: 257,
    y: 410,
    name: 'Kaiete',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 132,
    x: 264,
    y: 381,
    name: 'Sinope',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 133,
    x: 371,
    y: 725,
    name: 'Emporion',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 134,
    x: 497,
    y: 767,
    name: 'Gythio',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 135,
    x: 571,
    y: 241,
    name: 'Madytos',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Combattants a l\'epee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 136,
    x: 283,
    y: 638,
    name: 'Pteleum',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 137,
    x: 723,
    y: 648,
    name: 'Knossos',
    type: 'PROD T',
    bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 138,
    x: 256,
    y: 605,
    name: 'Vrokastro',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 139,
    x: 698,
    y: 325,
    name: 'Decelie',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 140,
    x: 751,
    y: 570,
    name: 'Amida',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 141,
    x: 536,
    y: 252,
    name: 'Larissa',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 142,
    x: 757,
    y: 428,
    name: 'Kavousi',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 143,
    x: 246,
    y: 497,
    name: 'Zankle',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 144,
    x: 306,
    y: 317,
    name: 'Tauromenion',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 145,
    x: 341,
    y: 306,
    name: 'Apamea',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 146,
    x: 666,
    y: 690,
    name: 'Myonia',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Griffons de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 147,
    x: 411,
    y: 256,
    name: 'Lamia',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 148,
    x: 524,
    y: 750,
    name: 'Artemita',
    type: 'NAZE',
    bonus: 'Augmente la valeur defensive des Cerberes de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  },
  {
    id: 149,
    x: 480,
    y: 246,
    name: 'Alexándreia',
    type: 'PROD T',
    bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true,
    conquest: false
  },
  {
    id: 150,
    x: 619,
    y: 736,
    name: 'Helorus',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false,
    conquest: false
  }
];

module.exports = { staticTemples };