const staticTemples = [
    {
      id: 101,
      x: 487,
      y: 476,
      name: 'Thronium',
      type: 'DEF',
      bonus: '15% CE',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 503,
      y: 452,
      name: 'Parthenopolis',
      type: 'OFF T',
      bonus: 'Contondant 8%',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 529,
      y: 451,
      name: 'Thèbes',
      type: 'Portail',
      bonus: 'Portail M54',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 551,
      y: 433,
      name: 'Histria',
      type: 'OFF T',
      bonus: '6% OFF T HORS UMV',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 673,
      y: 425,
      name: 'Myos',
      type: 'Portail',
      bonus: 'Portail M64',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 644,
      y: 358,
      name: 'Smyrna',
      type: 'OFF T',
      bonus: '10% OFF CAVA',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 741,
      y: 482,
      name: 'Antipatrea',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 549,
      y: 352,
      name: 'Lekhaion',
      type: 'PROD NAV',
      bonus: '10% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 517,
      y: 376,
      name: 'Priene',
      type: 'PROD NAV',
      bonus: 'Augmente l\'effet de l\'appel de la mer de 15%',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 567,
      y: 342,
      name: 'Pitane',
      type: 'PROD NAV',
      bonus: '4.5% Durée',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 585,
      y: 315,
      name: 'Samothrace',
      type: 'Portail',
      bonus: 'Portail M53',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 553,
      y: 306,
      name: 'Cythera',
      type: 'OFF T',
      bonus: '10% CAVA',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 585,
      y: 315,
      name: 'Samothrace',
      type: 'Portail',
      bonus: 'Portail M53',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 533,
      y: 317,
      name: 'Tylissos',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 504,
      y: 305,
      name: 'Zakynthos',
      type: 'OFF T',
      bonus: '8% OFF CONTONDANT',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 518,
      y: 286,
      name: 'Hyele',
      type: 'OFF NAV',
      bonus: '8% BF',
      size: 'small',
      owner: 0,
      contest: 'tocomplete'
    },
    {
      id: 101,
      x: 579,
      y: 289,
      name: 'Sicyon',
      type: 'Portail',
      bonus: 'Portail M52',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 536,
      y: 254,
      name: 'Larissa',
      type: '3% OFF',
      bonus: '3% OFF',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 470,
      y: 364,
      name: 'Kallatis',
      type: 'OFF NAV',
      bonus: '5% OFF NAV',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 469,
      y: 391,
      name: 'Borysthenes',
      type: 'Portail',
      bonus: 'Portail M43',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 438,
      y: 373,
      name: 'Mylasa',
      type: '3% OFF',
      bonus: '3% OFF FH',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 409,
      y: 425,
      name: 'Samos',
      type: 'OFF T',
      bonus: '8% off contondant',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 402,
      y: 478,
      name: 'Sozopolis',
      type: 'DEF',
      bonus: '+15% DEF Archers',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 380,
      y: 462,
      name: 'Scione',
      type: 'OFF NAV',
      bonus: '+8% OFF BF',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 360,
      y: 486,
      name: 'Mulai',
      type: 'OFF NAV',
      bonus: '+10% VENT FAVORABLE',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 372,
      y: 505,
      name: 'Panticapaeum',
      type: 'Portail',
      bonus: 'Portail M35',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 335,
      y: 499,
      name: 'Gortyn',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 338,
      y: 459,
      name: 'Rhodes',
      type: 'PROD NAV',
      bonus: '6% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 321,
      y: 440,
      name: 'Élis',
      type: 'PROD T',
      bonus: '4.5% durée terr',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 308,
      y: 468,
      name: 'Chalcis',
      type: 'Portail',
      bonus: 'Portail M34',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 296,
      y: 495,
      name: 'Mallia',
      type: 'PROD T',
      bonus: '6% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 296,
      y: 495,
      name: 'Mallia',
      type: 'PROD T',
      bonus: '6% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 282,
      y: 461,
      name: 'Edessa',
      type: 'DEF',
      bonus: '+15% DEF CE',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 302,
      y: 400,
      name: 'Taras',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 303,
      y: 373,
      name: 'Gonnos',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 332,
      y: 356,
      name: 'Monastiraki',
      type: '3% OFF',
      bonus: '3% OFF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 306,
      y: 319,
      name: 'Tauromenion',
      type: '3% OFF',
      bonus: '3% OFF',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 341,
      y: 308,
      name: 'Apamea',
      type: '3% OFF',
      bonus: '3% OFF',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 374,
      y: 309,
      name: 'Itanos',
      type: 'Portail',
      bonus: 'Portail M33',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 432,
      y: 279,
      name: 'Pseira',
      type: 'Portail',
      bonus: 'Portail M42',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 449,
      y: 244,
      name: 'Morgantina',
      type: 'OFF NAV',
      bonus: '+8% OFF BF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 480,
      y: 248,
      name: 'Alexándreia',
      type: 'PROD T',
      bonus: '10% COÛT TERR',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 687,
      y: 566,
      name: 'Heraclea',
      type: 'OFF T',
      bonus: '+8% OFF TERR HORS UMV',
      size: 'small',
      owner: 0,
      contest: 'tocomplete'
    },
    {
      id: 101,
      x: 670,
      y: 599,
      name: 'Thoricus',
      type: 'Portail',
      bonus: 'Portail M65',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 611,
      y: 576,
      name: 'Rhêgion',
      type: 'OFF T',
      bonus: '+8% Contondant',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 701,
      y: 593,
      name: 'Kasmenai',
      type: 'DEF',
      bonus: '+15% DEF Archers',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 724,
      y: 592,
      name: 'Magnesia',
      type: 'PROD NAV',
      bonus: '10% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 648,
      y: 625,
      name: 'Kalamata',
      type: 'PROD NAV',
      bonus: '10% COÛT NAV',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 723,
      y: 650,
      name: 'Knossos',
      type: 'PROD T',
      bonus: '6% COÛT TERR',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 612,
      y: 688,
      name: 'Agrinion',
      type: 'Portail',
      bonus: 'Portail M66',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 590,
      y: 707,
      name: 'Kilkís',
      type: 'DEF',
      bonus: '+15% DEF HOPLITES',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 500,
      y: 728,
      name: 'Kepoi',
      type: 'Portail',
      bonus: 'Portail M57',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
    {
      id: 101,
      x: 582,
      y: 663,
      name: 'Pyrgos',
      type: 'Portail',
      bonus: 'Portail M56',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 579,
      y: 640,
      name: 'Pixous',
      type: 'REPROD T',
      bonus: '10% COÛT TERR',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 451,
      y: 676,
      name: 'Malacca',
      type: 'Portail',
      bonus: 'Portail M46',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 476,
      y: 690,
      name: 'Pharos',
      type: 'DEF',
      bonus: '2% DEF',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 258,
      y: 538,
      name: 'Pandosia',
      type: 'PROD T',
      bonus: '10% COÛT TERR',
      size: 'small',
      owner: 0,
      contest: 'secured'
    },
    {
      id: 101,
      x: 331,
      y: 611,
      name: 'Argos',
      type: 'OFF T',
      bonus: '8% Contondant',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 320,
      y: 629,
      name: 'Sparte',
      type: 'Portail',
      bonus: 'Portail M36',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 363,
      y: 642,
      name: 'Cnide',
      type: 'OFF NAV',
      bonus: '8% BF',
      size: 'small',
      owner: 0,
      contest: 'contested'
    },
    {
      id: 101,
      x: 358,
      y: 670,
      name: 'Alalcomenae',
      type: 'PROD T',
      bonus: '6% COÛT TERR',
      size: 'small',
      owner: 0,
      contest: 'none'
    },
  ];
  
  module.exports = { staticTemples };