// généré automatiquement par build_temples.js
const staticTemples = [
  {
    id: 1,
    x: 487,
    y: 507,
    name: 'Lissus',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 3,
    x: 475,
    y: 532,
    name: 'Percote',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 4,
    x: 486,
    y: 479,
    name: 'Thronium',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Combattants a l\'epee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 6,
    x: 487,
    y: 560,
    name: 'Dimale',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 7,
    x: 511,
    y: 559,
    name: 'Myre',
    type: 'NAZE',
    bonus: 'Retour des Enfers rend 15% d\'unites en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 9,
    x: 554,
    y: 504,
    name: 'Tomis',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 10,
    x: 455,
    y: 432,
    name: 'Dascylion',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 11,
    x: 456,
    y: 571,
    name: 'Selinus',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 12,
    x: 432,
    y: 490,
    name: 'Assus',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 13,
    x: 583,
    y: 529,
    name: 'Hermione',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 14,
    x: 581,
    y: 485,
    name: 'Amphicaea',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 16,
    x: 430,
    y: 513,
    name: 'Lapithos',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 17,
    x: 404,
    y: 530,
    name: 'Ithaque',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 18,
    x: 546,
    y: 597,
    name: 'Amphigeneia',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 19,
    x: 468,
    y: 589,
    name: 'Oenoe',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Meduses de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 20,
    x: 400,
    y: 501,
    name: 'Anthedon',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Sirenes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 21,
    x: 417,
    y: 461,
    name: 'Dodone',
    type: 'NAZE',
    bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 22,
    x: 603,
    y: 494,
    name: 'Kelenderis',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 23,
    x: 569,
    y: 580,
    name: 'Haliarte',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 24,
    x: 489,
    y: 597,
    name: 'Tenedos',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 29,
    x: 605,
    y: 433,
    name: 'Laodicea',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 30,
    x: 512,
    y: 629,
    name: 'Koukounaries',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Archers de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 32,
    x: 601,
    y: 412,
    name: 'Orchomene',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 33,
    x: 490,
    y: 369,
    name: 'Cynossema',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 37,
    x: 375,
    y: 419,
    name: 'Ambracie',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Spartes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 38,
    x: 502,
    y: 652,
    name: 'Amphissa',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 40,
    x: 433,
    y: 627,
    name: 'Naupactus',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 41,
    x: 550,
    y: 632,
    name: 'Palaikastro',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 42,
    x: 646,
    y: 472,
    name: 'Masis',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 43,
    x: 367,
    y: 551,
    name: 'Maroneia',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 44,
    x: 400,
    y: 404,
    name: 'Vathypetros',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 45,
    x: 526,
    y: 346,
    name: 'Kourion',
    type: 'NAZE',
    bonus: 'Mariage donne 120 ressources en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 47,
    x: 578,
    y: 369,
    name: 'Akragas',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 49,
    x: 626,
    y: 440,
    name: 'Thurii',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive de toutes les unites de 2%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 50,
    x: 640,
    y: 501,
    name: 'Tenea',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 51,
    x: 667,
    y: 512,
    name: 'Odessos',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 54,
    x: 661,
    y: 457,
    name: 'Mutilene',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Erinyes de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 55,
    x: 396,
    y: 381,
    name: 'Doriskos',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 56,
    x: 387,
    y: 628,
    name: 'Phaselis',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 57,
    x: 351,
    y: 591,
    name: 'Lefkandi',
    type: 'PROD NAV',
    bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 58,
    x: 613,
    y: 377,
    name: 'Argyroupoli',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 60,
    x: 642,
    y: 579,
    name: 'Tanagra',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 20%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 62,
    x: 350,
    y: 569,
    name: 'Orestias',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement bireme de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 64,
    x: 669,
    y: 485,
    name: 'Bhrytos',
    type: '3% OFF',
    bonus: 'Augmente la valeur offensive de toutes les unites de 3%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 65,
    x: 648,
    y: 409,
    name: 'Olynthus',
    type: 'PROD NAV',
    bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 66,
    x: 433,
    y: 341,
    name: 'Messene',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 79,
    x: 507,
    y: 694,
    name: 'Amaseia',
    type: 'NAZE',
    bonus: 'Retour des Enfers rend 15% d\'unites en plus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 82,
    x: 346,
    y: 628,
    name: 'Stymphalos',
    type: 'OFF T',
    bonus: 'Augmente le bonus de concentration de la chasseresse de 10% supplementaires',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 84,
    x: 656,
    y: 380,
    name: 'Athmonia',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 86,
    x: 289,
    y: 564,
    name: 'Kimmerikon',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 87,
    x: 524,
    y: 719,
    name: 'Bassae',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 90,
    x: 369,
    y: 333,
    name: 'Halieis',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Frondeurs de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 94,
    x: 696,
    y: 446,
    name: 'Troie',
    type: 'NAZE',
    bonus: 'Augmente les valeurs offensive et defensive de Hydres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 95,
    x: 655,
    y: 647,
    name: 'Rizinia',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de toutes les unites Mythique de 5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 98,
    x: 719,
    y: 467,
    name: 'Akroinon',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 99,
    x: 320,
    y: 627,
    name: 'Sparte',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 101,
    x: 358,
    y: 670,
    name: 'Alalcomenae',
    type: 'PROD T',
    bonus: 'Réduit le coût des unités terrestres de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: true
  },
  {
    id: 102,
    x: 722,
    y: 518,
    name: 'Akrai',
    type: 'MIXTE',
    bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 103,
    x: 297,
    y: 584,
    name: 'Heliopolis',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 106,
    x: 641,
    y: 682,
    name: 'Mesembria',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 107,
    x: 349,
    y: 329,
    name: 'Methana',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 108,
    x: 402,
    y: 275,
    name: 'Gournia',
    type: 'OFF T',
    bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 109,
    x: 699,
    y: 361,
    name: 'Nymphaion',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 111,
    x: 568,
    y: 264,
    name: 'Dyme',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 112,
    x: 721,
    y: 436,
    name: 'Pactye',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 114,
    x: 746,
    y: 519,
    name: 'Naucratis',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 115,
    x: 665,
    y: 334,
    name: 'Platees',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 117,
    x: 263,
    y: 434,
    name: 'Metapontum',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 121,
    x: 286,
    y: 602,
    name: 'Ephyra',
    type: 'NAZE',
    bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 122,
    x: 735,
    y: 553,
    name: 'Bouthroton',
    type: 'NAZE',
    bonus: 'Augmente la puissance offensive de Meduses de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 123,
    x: 428,
    y: 716,
    name: 'Methumna',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 125,
    x: 282,
    y: 413,
    name: 'Patras',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 126,
    x: 713,
    y: 400,
    name: 'Ankon',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 127,
    x: 648,
    y: 282,
    name: 'Megare',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 128,
    x: 678,
    y: 312,
    name: 'Leibethra',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 129,
    x: 278,
    y: 364,
    name: 'Hyettos',
    type: 'NAZE',
    bonus: 'Augmente les valeurs offensive et defensive de Centaures de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 131,
    x: 257,
    y: 410,
    name: 'Kaiete',
    type: 'PROD NAV',
    bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 132,
    x: 264,
    y: 381,
    name: 'Sinope',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 133,
    x: 371,
    y: 725,
    name: 'Emporion',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 134,
    x: 497,
    y: 767,
    name: 'Gythio',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 135,
    x: 571,
    y: 241,
    name: 'Madytos',
    type: 'DEF',
    bonus: 'Augmente la valeur defensive des Combattants a l\'epee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 136,
    x: 283,
    y: 638,
    name: 'Pteleum',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 138,
    x: 256,
    y: 605,
    name: 'Vrokastro',
    type: 'PROD T',
    bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 139,
    x: 698,
    y: 325,
    name: 'Decelie',
    type: 'NAZE',
    bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 140,
    x: 751,
    y: 570,
    name: 'Amida',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 142,
    x: 757,
    y: 428,
    name: 'Kavousi',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 143,
    x: 246,
    y: 497,
    name: 'Zankle',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 146,
    x: 666,
    y: 690,
    name: 'Myonia',
    type: 'OFF T',
    bonus: 'Augmente la puissance offensive de Griffons de 8%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 147,
    x: 411,
    y: 256,
    name: 'Lamia',
    type: 'NAZE',
    bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 148,
    x: 524,
    y: 750,
    name: 'Artemita',
    type: 'NAZE',
    bonus: 'Augmente la valeur defensive des Cerberes de 10%',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  },
  {
    id: 150,
    x: 619,
    y: 736,
    name: 'Helorus',
    type: 'Portail',
    bonus: 'Portail vers Olympus',
    size: 'small',
    owner: 0,
    contest: 'none',
    focus: false
  }
];

module.exports = { staticTemples };